name: Build

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 0 * * *"
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Clone
      uses: actions/checkout@v2
      with:
        repository: 'kyokan/bob-wallet'
          
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
      
    - name: Debug
      run: pwd

    - name: Debug
      run: find .
      
    - name: Install deps
      run: npm i
    
    - name: Build
      run: npm run build && npx electron-builder build --linux --publish never
      
    - name: Debug
      run: find .
    
    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Latest"
        prerelease: true
        title: "Unofficial Bob Linux Build"
        files: |
          release/Bob-*.AppImage
